### ISSUE TITLE
Possibly broken architecture detection on Windows

### ISSUE THREAD

**Issue by coderanger** [chef/mixlib-install#188]
Was doing some testing on 32-bit Windows on EC2 and it was trying to install the x64 build. Didn't do a full debug on it, but the code in helpers.ps1 looks correct at first glance so maybe somewhere else?

If you want to repro try using a Kitchen config something like this:

```yaml
driver:
  name: ec2
  image_id: ami-f6a043e0
  instance_type: m1.medium
```

Given how few people actually use 32-bit Windows this is probably safely very low priority :-)
